### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140035900785152:ec  

### ISSUE THREAD

**Issue by sams898** [MBoemo/DNAscent#16]
Hello,

When I run the detect function, I get about halfway through the calling before getting the error "HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140035900785152:ec" that causes the read to fail and the process to core dump. All the permissions are open. Is there a way that I can stop this from happening?

Here is the full message:
"Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140628066390528:ec  failed:    1
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file:
Aborted (core dumped)"

Thank you! 
Sam

**Comment by sams898** [comment]
I actually found some other code that resolved it, thanks!

**Comment by zhanwen-cheng** [comment]
Hi, how do you solve this problem? I met the same issuse as you do.

**Comment by ShuangqiWang** [comment]
Hi Dr. Michael and all friends, 
Could you help me solve this problem if you know the answer? I checked #25 but I think my error is kind of different with #25 because It did not mention which fast5 has problem. Thanks very much! Here is my error: 

2024-04-26 22:22:40.424402: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'serving_default_input_3' with dtype float and shape [?,?,20,1]
	 [[{{node serving_default_input_3}}]]
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140678323480320:n15sec  failed:     68  
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: 
Aborted (core dumped)

**Comment by MBoemo** [comment]
@ShuangqiWang would you mind pasting the first few lines of the sequencing summary file? It looks like ONT have changed the format in some cases, particularly for onboard basecalling. We pushed a quick fix a few days ago (https://github.com/MBoemo/DNAscent/issues/49) but we're going to push a more robust fix for this in the coming days.

**Comment by ShuangqiWang** [comment]
Dear Dr. Michael,

Thank you for your swift response to my previous query.
Here is the first 2 lines of the sequencing summary file: 
filename_fastq	filename_fast5	filename_pod5	parent_read_id	read_id	run_id	channel	mux	minknow_events	start_time	duration	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	pore_typeexperiment_id	sample_id	end_reason	alias	type	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index
FAX32607_fail_unclassified_23fdcb64_16578251_0.fastq.gz	-	FAX32607_fail_unclassified_23fdcb64_16578251_0.pod5	c158aad0-25a5-4672-af2e-aa4a83e543b3	c158aad0-25a5-4672-af2e-aa4a83e543b3	1657825179ea01094bd2a1c5759a08f0a0781a70	301	1	1265	44.639400	2.033400	FALSE	44.641400	1692	2.031400	642	6.276084	0.000000	85.437515	25.448195	not_set	qiao2	Qiao2	signal_positive	unclassified	na	unclassified	NB02_var1	NB	var1	53.333332	NB02_FWD	53.333332	AGGTTAAACAGACGACTACAAACGGAATCGACAGCACCT	AAAACAACTTTACAAACAGAGATCAACCAGCACCCT	36	36	NB02_REV	11.416667GGTGCTGTCGATTCCGTTTGTAGTCGTCTGTTTAACCTTAGCAAT	GCTCTGTAACAAAGGTTCCTTCACAAACCTTAACTTCT	38	43

You may noticed that the 'filename_fast5' column in our sequencing summary file contains dashes (-) because the sequencing center provided us pod5 files instead of fast5 files. Thus, I did not use your 'dnascent index' to generate dnascent.index file. I converted these pod5 files to fast5 files prior to processing.  And manually generated a dnascent.index file likewise as follows (top 3 lines): 
#bulk
ae69ddf1-4627-4099-b97c-df0117eb6607	/mnt/1403f26c-e917-4cd7-afae-1b3f005ff19a/shuangqi_files/SisterPore-C_repair/rawdata/fast5_pass_Qiao_2h_barcode01/FAX32607_pass_barcode01_23fdcb64_16578251_0.fast5
4fe1ae7d-b34d-4a24-a8fd-0149285207d2	/mnt/1403f26c-e917-4cd7-afae-1b3f005ff19a/shuangqi_files/SisterPore-C_repair/rawdata/fast5_pass_Qiao_2h_barcode01/FAX32607_pass_barcode01_23fdcb64_16578251_0.fast5

When running DNAscent detect, there was some output (I got the EdU/BrdU ratio of hundands of reads) but it was interrupted with the previously mentioned HDF5 errors.

Thank you for your time and help!

**Comment by TeriCheng** [comment]
Hello, chipping in for a similar issue. After successfully indexing with the P2Solo fix  (#49), I encountered the same kind of error when I was running detect. For reference, we generated fast5 (not POD5), and we manually converted the fast5 to pod5 before manually basecalling with dorado. Could the error here be linked to incompatibility between these manual steps with the sequencing_summary.txt?

Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140037207357184:r35min19sec  failed:       26   
  #000: H5G.c line 467 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: H5Gint.c line 320 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140037207357184:
  #000: H5G.c line 812 in H5Gclose(): not a group
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140037207357184:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140036712417024:r31min 2sec  failed:       80    
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file:
