### ISSUE TITLE
DNAscent v3 with BrdU only

### ISSUE THREAD

**Issue by dariober** [MBoemo/DNAscent#31]
Hello again! We have sequencing data pulsed with BrdU only. Am I correct in saying that DNAscent v3 is not suitable for BrdU only? 

I see from [here](https://dnascent.readthedocs.io/en/latest/forkSense.html#usage) that *DNAscent forkSense is not compatible with legacy HMM-based detection or BrdU-only detection*. 

Would it be sensible to run `detect` on v3 and `forkSense` on v2? I guess the answer is no, better to stick to the latest version 2 throughout, but I wanted to check whether there are other options.

**Comment by MBoemo** [comment]
In terms of calling the position BrdU, we've found that the performance of v3.1.2 is comparable to v2.0.2, despite v3.1.2 having the extra possibility of EdU to contend with. If your data only has BrdU in it, and if you're just interested in the position of the analogue, you could probably use either one. What you can't do (and what that line in the documentation is getting at) is run DNAscent detect on v3.1.2 and then use DNAscent forkSense from v2.0.2 on the output (or vice versa). That's because the format of the detect output changed a bit between releases. It's also worth noting that the forkSense executable in v3.1.2 is expecting to be able to discern fork direction from EdU and BrdU, whereas forkSense in v2.0.2 was designed to measure fork direction from BrdU alone. So if you're trying to detect forks on BrdU-only data, definitely stick with v2.0.2.
